# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.29)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS fltk::z fltk::png fltk::jpeg fltk::fltk fltk::forms fltk::images fltk::gl)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target fltk::z
add_library(fltk::z STATIC IMPORTED)

# Create imported target fltk::png
add_library(fltk::png STATIC IMPORTED)

set_target_properties(fltk::png PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "HAVE_PNG_H=1;HAVE_PNG_GET_VALID=1;HAVE_PNG_SET_TRNS_TO_ALPHA=1"
  INTERFACE_INCLUDE_DIRECTORIES "/home/et/gosrc/go-fltk/fltk_build/fltk/png"
  INTERFACE_LINK_LIBRARIES "fltk::z"
)

# Create imported target fltk::jpeg
add_library(fltk::jpeg STATIC IMPORTED)

set_target_properties(fltk::jpeg PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/et/gosrc/go-fltk/fltk_build/fltk/jpeg"
)

# Create imported target fltk::fltk
add_library(fltk::fltk STATIC IMPORTED)

set_target_properties(fltk::fltk PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/et/gosrc/go-fltk/fltk_build/build/src/..;/home/et/gosrc/go-fltk/fltk_build/fltk/src/.."
  INTERFACE_LINK_DIRECTORIES "/home/et/gosrc/go-fltk/fltk_build/build/src/../lib"
  INTERFACE_LINK_LIBRARIES "/usr/lib/libdl.a;/usr/lib/libSM.so;/usr/lib/libICE.so;/usr/lib/libX11.so;/usr/lib/libXext.so;/usr/lib/libXinerama.so;/usr/lib/libXfixes.so;/usr/lib/libXcursor.so;/usr/lib/libXrender.so;/usr/lib/libpango-1.0.so;/usr/lib/libpangocairo-1.0.so;/usr/lib/libgobject-2.0.so;/usr/lib/libglib-2.0.so;/usr/lib/libharfbuzz.so;/usr/lib/libcairo.so;/usr/lib/libpangoxft-1.0.so;/usr/lib/libpangoft2-1.0.so;/usr/lib/libfontconfig.so;/usr/lib/libfreetype.so;/usr/lib/libXft.so"
)

# Create imported target fltk::forms
add_library(fltk::forms STATIC IMPORTED)

set_target_properties(fltk::forms PROPERTIES
  INTERFACE_LINK_LIBRARIES "fltk::fltk"
)

# Create imported target fltk::images
add_library(fltk::images STATIC IMPORTED)

set_target_properties(fltk::images PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/et/gosrc/go-fltk/fltk_build/fltk/jpeg"
  INTERFACE_LINK_LIBRARIES "fltk::fltk;\$<LINK_ONLY:fltk::png>;\$<LINK_ONLY:fltk::jpeg>"
)

# Create imported target fltk::gl
add_library(fltk::gl STATIC IMPORTED)

set_target_properties(fltk::gl PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include;/usr/include"
  INTERFACE_LINK_LIBRARIES "-L/usr/lib;-L/usr/lib;-lX11;-lGLU;-lGL;fltk::fltk;/usr/lib/libdl.a;/usr/lib/libSM.so;/usr/lib/libICE.so;/usr/lib/libX11.so;/usr/lib/libXext.so;/usr/lib/libXinerama.so;/usr/lib/libXfixes.so;/usr/lib/libXcursor.so;/usr/lib/libXrender.so;/usr/lib/libpango-1.0.so;/usr/lib/libpangocairo-1.0.so;/usr/lib/libgobject-2.0.so;/usr/lib/libglib-2.0.so;/usr/lib/libharfbuzz.so;/usr/lib/libcairo.so;/usr/lib/libpangoxft-1.0.so;/usr/lib/libpangoft2-1.0.so;/usr/lib/libfontconfig.so;/usr/lib/libfreetype.so;/usr/lib/libXft.so"
)

# Import target "fltk::z" for configuration "Release"
set_property(TARGET fltk::z APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(fltk::z PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/home/et/gosrc/go-fltk/fltk_build/build/lib/libfltk_z.a"
  )

# Import target "fltk::png" for configuration "Release"
set_property(TARGET fltk::png APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(fltk::png PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/home/et/gosrc/go-fltk/fltk_build/build/lib/libfltk_png.a"
  )

# Import target "fltk::jpeg" for configuration "Release"
set_property(TARGET fltk::jpeg APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(fltk::jpeg PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/home/et/gosrc/go-fltk/fltk_build/build/lib/libfltk_jpeg.a"
  )

# Import target "fltk::fltk" for configuration "Release"
set_property(TARGET fltk::fltk APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(fltk::fltk PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C;CXX"
  IMPORTED_LOCATION_RELEASE "/home/et/gosrc/go-fltk/fltk_build/build/lib/libfltk.a"
  )

# Import target "fltk::forms" for configuration "Release"
set_property(TARGET fltk::forms APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(fltk::forms PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/home/et/gosrc/go-fltk/fltk_build/build/lib/libfltk_forms.a"
  )

# Import target "fltk::images" for configuration "Release"
set_property(TARGET fltk::images APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(fltk::images PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/home/et/gosrc/go-fltk/fltk_build/build/lib/libfltk_images.a"
  )

# Import target "fltk::gl" for configuration "Release"
set_property(TARGET fltk::gl APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(fltk::gl PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/home/et/gosrc/go-fltk/fltk_build/build/lib/libfltk_gl.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
